# Generated by Django 4.0.4 on 2022-04-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(default='normal', max_length=35)),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('category', models.CharField(max_length=35)),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_on', models.DateField(blank=True, null=True)),
                ('solved_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='not started', max_length=35)),
                ('urgency', models.CharField(default='not urgent', max_length=20)),
                ('opened', models.BooleanField(default=False)),
                ('added_by_category', models.CharField(default='admin', max_length=35)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_added_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.unit')),
            ],
        ),
    ]
