# Generated by Django 4.0.4 on 2022-04-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_request_authorized_alarm_request_authorized_enter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
