# Generated by Django 4.0.4 on 2022-04-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_alter_request_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='action_title',
        ),
        migrations.AddField(
            model_name='service',
            name='arrived',
            field=models.CharField(default='no', max_length=35),
        ),
        migrations.AddField(
            model_name='service',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_assigned_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
