# Generated by Django 4.0.4 on 2022-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_action_title_service_arrived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='begun_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
