# Generated by Django 4.0.4 on 2022-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_request_begun_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='authorized_alarm',
            field=models.CharField(default='False', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='authorized_pet',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
