# Generated by Django 4.0.4 on 2022-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_request_budget_end_request_budget_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='budget_amount',
            field=models.IntegerField(default=0),
        ),
    ]
