# Generated by Django 4.0.4 on 2022-04-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_request_budget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time_in',
            field=models.CharField(blank=True, default='8:00 AM', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_out',
            field=models.CharField(blank=True, default='12:15 PM', max_length=10, null=True),
        ),
    ]
