# Generated by Django 4.0.4 on 2022-04-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_unit_owned_by_alter_unit_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='total_renovation',
            new_name='total_renovation_costs',
        ),
    ]
