# Generated by Django 4.0.4 on 2022-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_total_renovation_unit_total_renovation_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='appliance_package',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='blinds',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='cabinets',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='cabinets_hardware',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='carpet',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='flooring',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='misc',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='paint_contractor',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='quartz_counter_top',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='resurface',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='tub_tile',
        ),
        migrations.AddField(
            model_name='unit',
            name='random_value',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_category',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
