# Generated by Django 4.0.4 on 2022-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_unit_appliance_package_remove_unit_blinds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_designation',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
