# Generated by Django 4.0.4 on 2022-04-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_unit_city_unit_country_unit_neighborhood_unit_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='city',
            field=models.CharField(default='California', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='country',
            field=models.CharField(default='United States', max_length=50),
        ),
    ]
