# Generated by Django 4.0.4 on 2022-04-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_unit_unit_number_alter_unit_unit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_name',
            new_name='property_name',
        ),
    ]
